# Generated by Django 4.2.4 on 2023-09-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ProjetoApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Forum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200, unique=True)),
                ("descricao", models.TextField(blank=True, null=True)),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="forum_images/"),
                ),
            ],
        ),
    ]
