# Generated by Django 4.2.4 on 2023-09-27 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ProjetoApp", "0002_forum"),
    ]

    operations = [
        migrations.AddField(
            model_name="postagem",
            name="forum",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="postagens",
                to="ProjetoApp.forum",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="forum",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
