# Generated by Django 4.2.5 on 2023-09-28 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProjetoApp', '0003_postagem_forum_alter_forum_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
